nohup: ignoring input
Global seed set to 42
True
Not from scratch
rese:model_gin
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Using Rotation Embedding
Pre-processed data found: /media/ext_disk/zhenfang/dataset/davis/processed/davis_train_mols.pt, loading ...
seq_train_dataset: <class 'pandas.core.series.Series'>
seq_train_dataset: <class 'loader.SeqDataset'>
scaffold
fold: 0
/home/zhenfang/anaconda3/envs/pytorch_3.8/lib/python3.8/site-packages/torch_geometric/deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
Traceback (most recent call last):
  File "train_davis_model1_2_layer_multi_heads.py", line 702, in <module>
    train_loss=train(args, epoch, model, device, train_loader, optimizer)
  File "train_davis_model1_2_layer_multi_heads.py", line 578, in train
    pred=model(seq_data_list,B,C)#model is error
  File "/home/zhenfang/anaconda3/envs/pytorch_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhenfang/esm/SeqMolSmile_model1_2_layer_multi_head.py", line 737, in forward
    x11=  self.mol_cross_attention(x1,x1,x2) 
  File "/home/zhenfang/anaconda3/envs/pytorch_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhenfang/esm/SeqMolSmile_model1_2_layer_multi_head.py", line 228, in forward
    values = self.embedding(values)
  File "/home/zhenfang/anaconda3/envs/pytorch_3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhenfang/anaconda3/envs/pytorch_3.8/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/home/zhenfang/anaconda3/envs/pytorch_3.8/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
